### ISSUE TITLE
certain syntax classes not recognized

### ISSUE THREAD

**Issue by camoy** [michaelballantyne/syntax-spec#10]
Certain syntax classes, in particular `string`, `bytes`, `regexp`, and `byte-regexp` are not recognized as syntax classes because `syntax/parse` defines them [specially](https://github.com/racket/racket/blob/ec939cd539d47bbe9db533683ae9dcf83e15d061/racket/collects/syntax/parse/private/lib.rkt#L69). Perhaps `syntax/parse` could do something different?

**Comment by michaelballantyne** [comment]
Fixed in https://github.com/michaelballantyne/syntax-spec/commit/156b6da1f3ee4cf0eaaa633d9f459d6d96b6bbfd
