### ISSUE TITLE
Group homogeneity error highlights only the ...

### ISSUE THREAD

**Issue by michaelballantyne** [michaelballantyne/syntax-spec#43]
![image](https://github.com/user-attachments/assets/61a21397-d302-4fe1-8ffe-ffbd61bd7f11)

It would probably be best to highlight the group that is repeated, or the group and the ellipsis together

**Comment by quasarbright** [comment]
should say "cannot mix imports or exports with other kinds of binding specs"

**Comment by michaelballantyne** [comment]
This one seems related, the ... is getting highlighted instead of the group:

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/858fb051-8951-4bcc-902b-37d51f5fa3f5">

**Comment by quasarbright** [comment]
the stx field of an ellipsis bspec should just be the ellipsized spec and the ellipsis

**Comment by michaelballantyne** [comment]
And another order check:

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/8e738601-ca34-4b76-995b-6c449cd5da14">

**Comment by quasarbright** [comment]
to fix ...+ not working, match on datum instead of literal for it in `compile/syntax-spec.rkt`
